apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kmqz0wq79-python 
  janus-idp.io/tekton: kmqz0wq79-python
  backstage.io/kubernetes-id: kmqz0wq79-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kmqz0wq79-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml