apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kmqz0wq79-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:d2e8948b199e1612b814a4ff62d07acdf279a1d9@sha256:d74afffb858ea32ddb98601e762abbd55305d414947bc4bd847ff448cb2e9d9f
          name: container-image
